import type { SurveyQuestion } from "./types";

export const defaultQuestions: SurveyQuestion[] = [
  {
    id: "q1",
    text: {
      fa: "چقدر از خدمات عمومی ما راضی بودید؟",
      en: "How satisfied were you with our general services?",
      ar: "ما مدى رضاك عن خدماتنا العامة؟",
    },
    type: "rating",
    category: "general",
    required: true,
    isPrimary: true,
    order: 1,
    active: true,
  },
  {
    id: "q2",
    text: {
      fa: "آیا امکانات موجود برای شما کافی بودند؟",
      en: "Were the available facilities sufficient for you?",
      ar: "هل كانت المرافق المتاحة كافية لك؟",
    },
    type: "rating",
    category: "general",
    required: true,
    isPrimary: true,
    order: 2,
    active: true,
  },
  {
    id: "q3",
    text: {
      fa: "چقدر راحت توانستید خدمات را دریافت کنید؟",
      en: "How easily could you receive the services?",
      ar: "ما مدى سهولة حصولك على الخدمات؟",
    },
    type: "rating",
    category: "general",
    required: true,
    isPrimary: true,
    order: 3,
    active: true,
  },
  {
    id: "q4",
    text: {
      fa: "آیا انتظار شما از خدمات ما برآورده شد؟",
      en: "Were your expectations of our services met?",
      ar: "هل تم تلبية توقعاتك من خدماتنا؟",
    },
    type: "rating",
    category: "general",
    required: true,
    isPrimary: true,
    order: 4,
    active: true,
  },
  {
    id: "q5",
    text: {
      fa: "آیا به دوستان و خانواده خود این خدمات را توصیه می‌کنید؟",
      en: "Would you recommend these services to friends and family?",
      ar: "هل توصي بهذه الخدمات لأصدقائك وعائلتك؟",
    },
    type: "rating",
    category: "general",
    required: true,
    isPrimary: true,
    order: 5,
    active: true,
  },
  {
    id: "q6",
    text: {
      fa: "چقدر از رفتار و برخورد این کارمند راضی بودید؟",
      en: "How satisfied were you with this employee's behavior?",
      ar: "ما مدى رضاك عن سلوك هذا الموظف؟",
    },
    type: "rating",
    category: "employee_specific",
    required: true,
    isPrimary: false,
    order: 6,
    active: true,
  },
  {
    id: "q7",
    text: {
      fa: "آیا این کارمند به تمام سوالات شما پاسخ داد؟",
      en: "Did this employee answer all your questions?",
      ar: "هل أجاب هذا الموظف على جميع أسئلتك؟",
    },
    type: "rating",
    category: "employee_specific",
    required: true,
    isPrimary: false,
    order: 7,
    active: true,
  },
  {
    id: "q8",
    text: {
      fa: "آیا این کارمند نیازهای شما را به خوبی شناسایی کرد؟",
      en: "Did this employee identify your needs well?",
      ar: "هل حدد هذا الموظف احتياجاتك بشكل جيد؟",
    },
    type: "rating",
    category: "employee_specific",
    required: true,
    isPrimary: false,
    order: 8,
    active: true,
  },
  {
    id: "q9",
    text: {
      fa: "آیا این کارمند به موقع و دقیق خدمت‌رسانی کرد؟",
      en: "Did this employee provide timely and accurate service?",
      ar: "هل قدم هذا الموظف خدمة في الوقت المناسب ودقيقة؟",
    },
    type: "rating",
    category: "employee_specific",
    required: true,
    isPrimary: false,
    order: 9,
    active: true,
  },
  {
    id: "q10",
    text: {
      fa: "آیا درک و تخصص این کارمند بر رضایت شما تاثیر داشت؟",
      en: "Did this employee's understanding and expertise affect your satisfaction?",
      ar: "هل أثر فهم وخبرة هذا الموظف على رضاك؟",
    },
    type: "rating",
    category: "employee_specific",
    required: true,
    isPrimary: false,
    order: 10,
    active: true,
  },
  {
    id: "q11",
    text: {
      fa: "آیا این خدمت برای شما مفید بود؟",
      en: "Was this service useful for you?",
      ar: "هل كانت هذه الخدمة مفيدة لك؟",
    },
    type: "rating",
    category: "service",
    required: true,
    isPrimary: false,
    order: 11,
    active: true,
  },
  {
    id: "q12",
    text: {
      fa: "چقدر کیفیت محصول/خدمت دریافتی مطابق با انتظارات شما بود؟",
      en: "How much did the quality of the product/service match your expectations?",
      ar: "ما مدى مطابقة جودة المنتج/الخدمة لتوقعاتك؟",
    },
    type: "rating",
    category: "service",
    required: true,
    isPrimary: false,
    order: 12,
    active: true,
  },
  {
    id: "q13",
    text: {
      fa: "آیا این محصول/خدمت در حل مشکل شما موثر بود؟",
      en: "Was this product/service effective in solving your problem?",
      ar: "هل كان هذا المنتج/الخدمة فعالاً في حل مشكلتك؟",
    },
    type: "rating",
    category: "service",
    required: true,
    isPrimary: false,
    order: 13,
    active: true,
  },
  {
    id: "q14",
    text: {
      fa: "چقدر تمایل دارید از خدمات ما مجدداً استفاده کنید؟",
      en: "How willing are you to use our services again?",
      ar: "ما مدى استعدادك لاستخدام خدماتنا مرة أخرى؟",
    },
    type: "rating",
    category: "additional",
    required: true,
    isPrimary: false,
    order: 14,
    active: true,
  },
  {
    id: "q15",
    text: {
      fa: "آیا شما برای خرید یا استفاده مجدد از خدمات ما انگیزه‌ای دارید؟",
      en: "Do you have motivation to purchase or use our services again?",
      ar: "هل لديك الدافع لشراء أو استخدام خدماتنا مرة أخرى؟",
    },
    type: "rating",
    category: "additional",
    required: true,
    isPrimary: false,
    order: 15,
    active: true,
  },
  {
    id: "q16",
    text: {
      fa: "آیا با اعضای دیگر تیم به اشتراک گذاشتید که از خدمات ما استفاده کنید؟",
      en: "Have you shared with other team members to use our services?",
      ar: "هل شاركت مع أعضاء آخرين في الفريق لاستخدام خدماتنا؟",
    },
    type: "yes_no",
    category: "additional",
    required: true,
    isPrimary: false,
    order: 16,
    active: true,
  },
  {
    id: "q17",
    text: {
      fa: "لطفاً اگر پیشنهادی برای بهبود خدمات دارید، بنویسید.",
      en: "Please write if you have any suggestions for improving services.",
      ar: "يرجى الكتابة إذا كان لديك أي اقتراحات لتحسين الخدمات.",
    },
    type: "text",
    category: "feedback",
    required: false,
    isPrimary: false,
    order: 17,
    active: true,
  },
  {
    id: "q18",
    text: {
      fa: "آیا موضوع خاصی در تعامل با این کارمند شما را نگران کرد؟ لطفاً توضیح دهید.",
      en: "Did any particular issue in your interaction with this employee concern you? Please explain.",
      ar: "هل أثار أي موضوع معين في تفاعلك مع هذا الموظف قلقك؟ يرجى التوضيح.",
    },
    type: "text",
    category: "feedback",
    required: false,
    isPrimary: false,
    order: 18,
    active: true,
  },
  {
    id: "q19",
    text: {
      fa: "نظر شما درباره نحوه ارتباط این کارمند با شما چیست؟",
      en: "What is your opinion about how this employee communicated with you?",
      ar: "ما رأيك في طريقة تواصل هذا الموظف معك؟",
    },
    type: "text",
    category: "feedback",
    required: false,
    isPrimary: false,
    order: 19,
    active: true,
  },
];
